# Use a lightweight Node.js base image
FROM node:20.12.0-alpine3.19

# Set working directory to monorepo root
WORKDIR /app

# Copy package management files
COPY package.json package-lock.json turbo.json ./

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Build the application
RUN npm run build

EXPOSE 3000

# Start the application
CMD ["npm", "run", "run-docs-app"]